version: '3'
services:
  api:
    image: sample-express-app
    build: 
      dockerfile: ./dockerfiles/node/Dockerfile
    networks:
      - backend
    ports:
      - "3000:3000"
  
    mongodb:
      image: 'mongo'
      restart: always
      container_name: mongo-docker
      volumes:
        - 'data:/data/db'
      env_file:
        - './env/mongo.env'
      ports:
        - "27017:27017"

networks:
  backend:
    driver: bridge