version: '3'
services:
  api:
    image: sample-express-app
    build: 
      dockerfile: ./dockerfiles/node/Dockerfile
    networks:
      - backend
    ports:
      - "3000:3000"

networks:
  backend:
    driver: bridge