version: '3'
services:
  api:
    image: sample-express-app
    build:
      dockerfile: ./dockerfiles/node/Dockerfile
    networks:
      - backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: 'mongo'
    restart: always
    container_name: mongo-docker
    volumes:
      - 'data:/data/db'
    env_file:
      - './env/mongo.env'
    ports:
      - "27017:27017"
    networks:
      - backend

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    env_file:
      - './env/mongo-express.env'
    depends_on:
      - mongodb
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
